### ISSUE TITLE
Актуализация темы "культуры" при разработке.

### ISSUE THREAD

**Issue by useSLIDERorDUMB** [alhafram/Dwarium#90]
Во первых хотелось бы получить ответ, это мода такая, молча закрывать ишью и отменять пуллы без комментария? Эту моду привил тот же дегенерат, который использует тапскрипт очком своим, вместо головы? Я вообще молчу, про особенности и возможности тайпскрипта как такового, и понимаю что новички любят использовать его как типизированный js, но полистав буквально пару сервисов натыкаешься на ебучий караул, это даже не типизированный JS, а выборочно типизированный. Какого хуя у большей части проперти типизированы, а сама функция висит без типа? к чему тогда вообще TS на проекте? И как так получается, что типизировать проперти у функции получилось, а саму функцию нет? Это какой-то кибербуллинг в мире веб разработки? Просто порой читаешь код, и хочешь понять, "почему блять?!". UI конечно красивый, но над качеством кода следует поработать, не хорошая практика так использовать ts, и тем более молча дропать ишью и пуллы, особенно когда это БУКВАЛЬНО ЕДИНСТВЕННАЯ обратная связь про проекту на гите.

**Comment by useSLIDERorDUMB** [comment]
Ещё вопрос, в какую ветку актуально пушить пуллы с рефакторингом и прочими предложениями? Судя по тому, что на мой высер в гите в "мастер" даже молча пулл закрыть, тратят по 3 дня, то я делаю это где-то в не том месте.

**Comment by alhafram** [comment]
Иди помой рот и научись общаться. Потом пиши что то!)

**Comment by useSLIDERorDUMB** [comment]
> Иди помой рот и научись общаться. Потом пиши что то!)

Помыл, а ты руки и голову помоешь, прежде чем писать код?

**Comment by useSLIDERorDUMB** [comment]
Ну вот просто как такой код имеет право на жизнь? что это блять за мутант из js и попыток его типизировать?
`function convertToMs(minutes: number): number {
    return minutes * 60 * 1000
}`
Почему сервис аналитики вообще имеет тип файла ts, если кроме '.ts' в названии файла, тайпскрипт там даже мимо не проходил?
Почему блять в одном и том же сервисе, есть функция, тоже мутант к слову `async function loadExpiringItems(): Promise<ExpiringItemsContainer>` которая выделилась, и её типизировали и следом идёт это `async function handleExpiringItems()`

**Comment by useSLIDERorDUMB** [comment]
Почему енумы которые импортируются постоянно туда-сюда, обратно и используются чуть-ли не повсеместно, каждый по рофлу живёт в месте где понравилось, в какой-то момент придерживаться стайлгайда, и делать model с всем необходимым стало дурным тоном?

**Comment by useSLIDERorDUMB** [comment]
![image](https://user-images.githubusercontent.com/128195331/226539254-2e0f2a63-6fc0-47c6-8a94-46fbd4e812c3.png)
Вот это вообще как блять понимать? Мы зачем-то насильно и неявно преобразовываем в функции any в unknown, чтобы потом при вызове этой функции дополнительно всегда переприсваивать в эни?) Я не знаю сколько раз мне надо помыть рот и пройти курс психотерапии, чтобы взглянув на это не назвать это ну полным идиотизмом

**Comment by useSLIDERorDUMB** [comment]
В общем вопросов к проекту реально много, я могу перечислять их бесконечно, вопрос в том, в какую ветку это делать? Ответа на этот вопрос я так и не получил.
